import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSWR from "swr";
import { useEffect, useState } from "react";

export default function Home() {
  const [employees, setEmployees] = useState([]);

  const { mutate } = useSWR("/api/employees");

  useEffect(() => {
    async function startFetching() {
      const response = await fetch("/api/employees");
      const employeesList = await response.json();

      console.log("EMPLOYEES ", employeesList);

      setEmployees(employeesList);
    }

    startFetching();
  }, []);

  return (
    <>
      <Head>
        <title>Employee App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <button>Display all employees</button> */}
      {employees.map(({ _id, firstName, lastName, position, supervisor }) => (
        <li key={_id}>
          {firstName} {lastName} {position}
        </li>
      ))}
    </>
  );
}
