import Head from "next/head";
import { useState } from "react";
import DeleteEmployee from "./DeleteEmployee";

export default function Home() {
  const [employees, setEmployees] = useState([]);
  const [showData, setShowData] = useState(false);

  const fetchData = async () => {
    try {
      const response = await fetch("/api/employees");
      const data = await response.json();
      setEmployees(data);
      setShowData(true);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  const hideData = () => {
    setShowData(false);
  };

  const onDelete = () => {
    console.log("clicked on delete ");
  };

  return (
    <>
      <Head>
        <title>Employee App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={fetchData}>Fetch all employees</button>
      {/* {employees.map(({ _id, firstName, lastName, position, supervisor }) => (
        <li key={_id}>
          {firstName} {lastName} {position}
        </li>
      ))} */}

      {showData && employees && (
        <div>
          <button onClick={hideData}>Hide Data</button>
          <h2>Response Data:</h2>
          {/* <pre>{JSON.stringify(employees, null, 2)}</pre> */}
          <ul>
            {employees.map(
              ({ _id, firstName, lastName, position, supervisor }) => (
                <li key={_id}>
                  {firstName} {lastName} {position}
                  {/* <button onClick={onDelete}>DELETE</button> */}
                  <DeleteEmployee id={_id}>Delete</DeleteEmployee>
                </li>
              )
            )}
          </ul>
        </div>
      )}
    </>
  );
}
